events { worker_connections 1024; }

http {
    upstream my_node_cluster {
        # max_fails aur fail_timeout se Nginx samajh jayega ki container down hai
        server node-app:3000 max_fails=1 fail_timeout=2s; 
    }

    server {
        listen 80;

        location / {
            proxy_pass http://my_node_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # 👇 Yeh lines magic karengi: Agar ek container error ya timeout de, toh automatic dusre par jao
            proxy_next_upstream error timeout invalid_header http_502 http_503 http_504;
            proxy_next_upstream_tries 3;
            proxy_next_upstream_timeout 2s;
        }
    }
}
